//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.23 at 05:29:32 PM CEST 
//


package ebu.metadata_schema.ebucore_2014;

import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import eu.mikrosimage.xdmat.ebucore.helpers.AudioContentTypeHelper;


/**
 * <p>Java class for audioContentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="audioContentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="audioObjectIDRef" type="{http://www.w3.org/2001/XMLSchema}anyURI" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="loudnessMetadata" type="{urn:ebu:metadata-schema:ebuCore_2014}loudnessMetadataType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="audioContentID" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="audioContentName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="audioContentLanguage" type="{http://www.w3.org/2001/XMLSchema}language" />
 *       &lt;attribute name="dialogue" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "audioContentType", propOrder = {
		"audioObjectIDRef",
		"loudnessMetadata"
})
public class AudioContentType implements Comparable<AudioContentType>{
	
	/**
	 * Prefix for this type EBUCore String ID
	 */
	public static final java.lang.String PREFIX = "ACO_";

	@XmlSchemaType(name = "anyURI")
	protected Set<java.lang.String> audioObjectIDRef;
	protected LoudnessMetadataType loudnessMetadata;
	@XmlAttribute(name = "audioContentID")
	@XmlSchemaType(name = "anyURI")
	protected java.lang.String audioContentID;
	@XmlAttribute(name = "audioContentName")
	protected java.lang.String audioContentName;
	@XmlAttribute(name = "audioContentLanguage")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	@XmlSchemaType(name = "language")
	protected java.lang.String audioContentLanguage;
	@XmlAttribute(name = "dialogue")
	protected Integer dialogue;

	
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((audioContentID == null) ? 0 : audioContentID.hashCode());
		return result;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof AudioContentType)) {
			return false;
		}
		AudioContentType other = (AudioContentType) obj;
		if (audioContentID == null) {
			if (other.audioContentID != null) {
				return false;
			}
		} else if (!audioContentID.equals(other.audioContentID)) {
			return false;
		}
		return true;
	}

	@Override
	public int compareTo(AudioContentType other) {
		return AudioContentTypeHelper.getAudioContentIndexFromId(getAudioContentID()) -
				AudioContentTypeHelper.getAudioContentIndexFromId(other.getAudioContentID());
	}
	
	@Override
	public java.lang.String toString() {
		return getAudioContentID();
	}

	/**
	 * Gets the value of the audioObjectIDRef property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list,
	 * not a snapshot. Therefore any modification you make to the
	 * returned list will be present inside the JAXB object.
	 * This is why there is not a <CODE>set</CODE> method for the audioObjectIDRef property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getAudioObjectIDRef().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link java.lang.String }
	 * 
	 * 
	 */
	public Set<java.lang.String> getAudioObjectIDRef() {
		if (audioObjectIDRef == null) {
			audioObjectIDRef = new HashSet<java.lang.String>();
		}
		return this.audioObjectIDRef;
	}

	/**
	 * Gets the value of the loudnessMetadata property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link LoudnessMetadataType }
	 *     
	 */
	public LoudnessMetadataType getLoudnessMetadata() {
		return loudnessMetadata;
	}

	/**
	 * Sets the value of the loudnessMetadata property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link LoudnessMetadataType }
	 *     
	 */
	public void setLoudnessMetadata(LoudnessMetadataType value) {
		this.loudnessMetadata = value;
	}

	/**
	 * Gets the value of the audioContentID property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link java.lang.String }
	 *     
	 */
	public java.lang.String getAudioContentID() {
		return audioContentID;
	}

	/**
	 * Sets the value of the audioContentID property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link java.lang.String }
	 *     
	 */
	public void setAudioContentID(java.lang.String value) {
		this.audioContentID = value;
	}

	/**
	 * Gets the value of the audioContentName property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link java.lang.String }
	 *     
	 */
	public java.lang.String getAudioContentName() {
		return audioContentName;
	}

	/**
	 * Sets the value of the audioContentName property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link java.lang.String }
	 *     
	 */
	public void setAudioContentName(java.lang.String value) {
		this.audioContentName = value;
	}

	/**
	 * Gets the value of the audioContentLanguage property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link java.lang.String }
	 *     
	 */
	public java.lang.String getAudioContentLanguage() {
		return audioContentLanguage;
	}

	/**
	 * Sets the value of the audioContentLanguage property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link java.lang.String }
	 *     
	 */
	public void setAudioContentLanguage(java.lang.String value) {
		this.audioContentLanguage = value;
	}

	/**
	 * Gets the value of the dialogue property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link Integer }
	 *     
	 */
	public int getDialogue() {
		if (dialogue == null) {
			return  0;
		} else {
			return dialogue;
		}
	}

	/**
	 * Sets the value of the dialogue property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link Integer }
	 *     
	 */
	public void setDialogue(Integer value) {
		this.dialogue = value;
	}

}
