//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.23 at 05:29:32 PM CEST 
//


package ebu.metadata_schema.ebucore_2014;

import java.util.Comparator;
import java.util.HashSet;
import java.util.Set;
import java.util.TreeSet;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

import eu.mikrosimage.xdmat.ebucore_2014.helpers.AudioPackFormatTypeHelper;
import eu.mikrosimage.xdmat.ebucore_2014.helpers.AudioTrackUIDTypeHelper;


/**
 * <p>Java class for audioObjectType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="audioObjectType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="audioPackFormatIDRef" type="{http://www.w3.org/2001/XMLSchema}anyURI" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="audioObjectIDRef" type="{http://www.w3.org/2001/XMLSchema}anyURI" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="audioTrackUIDRef" type="{http://www.w3.org/2001/XMLSchema}anyURI" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="audioObjectID" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="audioObjectName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="start" type="{urn:ebu:metadata-schema:ebuCore_2014}timecodeType" />
 *       &lt;attribute name="duration" type="{urn:ebu:metadata-schema:ebuCore_2014}timecodeType" />
 *       &lt;attribute name="dialogue" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *       &lt;attribute name="importance" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="interact" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "audioObjectType", propOrder = {
    "audioPackFormatIDRef",
    "audioObjectIDRef",
    "audioTrackUIDRef"
})
public class AudioObjectType implements Comparable<AudioObjectType> {
	
	/**
	 * Prefix for this type EBUCore String ID
	 */
	public static final java.lang.String PREFIX = "AO_";

    @XmlSchemaType(name = "anyURI")
    protected Set<java.lang.String> audioPackFormatIDRef;
    @XmlSchemaType(name = "anyURI")
    protected Set<java.lang.String> audioObjectIDRef;
    @XmlSchemaType(name = "anyURI")
    protected Set<java.lang.String> audioTrackUIDRef;
    @XmlAttribute(name = "audioObjectID")
    @XmlSchemaType(name = "anyURI")
    protected java.lang.String audioObjectID;
    @XmlAttribute(name = "audioObjectName")
    protected java.lang.String audioObjectName;
    @XmlAttribute(name = "start")
    protected java.lang.String start;
    @XmlAttribute(name = "duration")
    protected java.lang.String duration;
    @XmlAttribute(name = "dialogue")
    protected Integer dialogue;
    @XmlAttribute(name = "importance")
    protected Integer importance;
    @XmlAttribute(name = "interact")
    protected java.lang.Boolean interact;

    @Override
    public int compareTo(AudioObjectType other) {
    	return other.getAudioObjectID().compareTo(getAudioObjectID());
    }
    
    @Override
    public java.lang.String toString() {
    	return getAudioObjectID();
    }
    
    /**
     * Gets the value of the audioPackFormatIDRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the audioPackFormatIDRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAudioPackFormatIDRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link java.lang.String }
     * 
     * 
     */
    public Set<java.lang.String> getAudioPackFormatIDRef() {
        if (audioPackFormatIDRef == null) {
            audioPackFormatIDRef = new TreeSet<java.lang.String>(new Comparator<java.lang.String>() {
            	@Override
            	public int compare(java.lang.String o1, java.lang.String o2) {
            		int index1 = AudioPackFormatTypeHelper.getAudioPackFormatIndexFromId(o1);
    				int index2 = AudioPackFormatTypeHelper.getAudioPackFormatIndexFromId(o2);
    				return index1-index2;
            	}
			});
        }
        return this.audioPackFormatIDRef;
    }

    /**
     * Gets the value of the audioObjectIDRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the audioObjectIDRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAudioObjectIDRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link java.lang.String }
     * 
     * 
     */
    public Set<java.lang.String> getAudioObjectIDRef() {
        if (audioObjectIDRef == null) {
            audioObjectIDRef = new HashSet<java.lang.String>();
        }
        return this.audioObjectIDRef;
    }

    /**
     * Gets the value of the audioTrackUIDRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the audioTrackUIDRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAudioTrackUIDRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link java.lang.String }
     * 
     * 
     */
    public Set<java.lang.String> getAudioTrackUIDRef() {
        if (audioTrackUIDRef == null) {
            audioTrackUIDRef = new TreeSet<java.lang.String>(new Comparator<java.lang.String>() {
            	@Override
            	public int compare(java.lang.String o1, java.lang.String o2) {
            		int index1 = AudioTrackUIDTypeHelper.getAudioTrackIndexFromUid(o1);
    				int index2 = AudioTrackUIDTypeHelper.getAudioTrackIndexFromUid(o2);
    				return index1-index2;
            	}
			});
        }
        return this.audioTrackUIDRef;
    }

    /**
     * Gets the value of the audioObjectID property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getAudioObjectID() {
        return audioObjectID;
    }

    /**
     * Sets the value of the audioObjectID property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setAudioObjectID(java.lang.String value) {
        this.audioObjectID = value;
    }

    /**
     * Gets the value of the audioObjectName property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getAudioObjectName() {
        return audioObjectName;
    }

    /**
     * Sets the value of the audioObjectName property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setAudioObjectName(java.lang.String value) {
        this.audioObjectName = value;
    }

    /**
     * Gets the value of the start property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getStart() {
        return start;
    }

    /**
     * Sets the value of the start property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setStart(java.lang.String value) {
        this.start = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setDuration(java.lang.String value) {
        this.duration = value;
    }

    /**
     * Gets the value of the dialogue property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getDialogue() {
        if (dialogue == null) {
            return  0;
        } else {
            return dialogue;
        }
    }

    /**
     * Sets the value of the dialogue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDialogue(Integer value) {
        this.dialogue = value;
    }

    /**
     * Gets the value of the importance property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getImportance() {
        return importance;
    }

    /**
     * Sets the value of the importance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setImportance(Integer value) {
        this.importance = value;
    }

    /**
     * Gets the value of the interact property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Boolean }
     *     
     */
    public java.lang.Boolean isInteract() {
        return interact;
    }

    /**
     * Sets the value of the interact property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Boolean }
     *     
     */
    public void setInteract(java.lang.Boolean value) {
        this.interact = value;
    }

}
