//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.23 at 05:29:32 PM CEST 
//


package ebu.metadata_schema.ebucore_2014;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * A set of references to lookup MXF essence IDs.
 * 
 * <p>Java class for audioMXFLookUpType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="audioMXFLookUpType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="packageUIDRef" type="{urn:ebu:metadata-schema:ebuCore_2014}PackageIDType"/>
 *         &lt;element name="trackIDRef" type="{http://www.w3.org/2001/XMLSchema}NCName"/>
 *         &lt;element name="channelIDRef" type="{http://www.w3.org/2001/XMLSchema}NCName"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "audioMXFLookUpType", propOrder = {
    "packageUIDRef",
    "trackIDRef",
    "channelIDRef"
})
public class AudioMXFLookUpType {

    @XmlElement(required = true)
    protected java.lang.String packageUIDRef;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected java.lang.String trackIDRef;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected java.lang.String channelIDRef;

    /**
     * Gets the value of the packageUIDRef property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getPackageUIDRef() {
        return packageUIDRef;
    }

    /**
     * Sets the value of the packageUIDRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setPackageUIDRef(java.lang.String value) {
        this.packageUIDRef = value;
    }

    /**
     * Gets the value of the trackIDRef property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getTrackIDRef() {
        return trackIDRef;
    }

    /**
     * Sets the value of the trackIDRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setTrackIDRef(java.lang.String value) {
        this.trackIDRef = value;
    }

    /**
     * Gets the value of the channelIDRef property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getChannelIDRef() {
        return channelIDRef;
    }

    /**
     * Sets the value of the channelIDRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setChannelIDRef(java.lang.String value) {
        this.channelIDRef = value;
    }

}
