//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.23 at 05:29:32 PM CEST 
//

/**
 * <p><em>The <strong>EBUCore</strong> is a metadata specification designed for users with different needs</em>.</p>
 *  <p>This is version 1.5 of the “<strong>EBUCore</strong>” metadata set.</p>
 *  <p><strong>EBUCore</strong> has been purposefully designed as a minimum and flexible list of attributes to describe audio 
 *  and video resources for a wide range of broadcasting applications including archives, exchange and production 
 *  in the context of a Service Oriented Architecture. It is also a metadata schema with well defined syntax 
 *  and semantics for easier implementation.</p>
 *  <p><strong>EBUCore</strong> is based on the Dublin Core to maximise interoperability with the community of Dublin Core 
 *  users such as the European Digital Library '<em>Europeana</em>'.</p>
 *  <p><strong>EBUCore</strong> 1.5 takes into account latest developments in the Semantic Web and Linked Open Data communities. 
 *  <strong>EBUCore</strong> 1.5 is available as a RDF ontology entirely compatible with the W3C Media Annotation Working Group 
 *  ontology, which model is common and based on the EBU Class Conceptual Data Model (EBU Tech 3351). 
 *  A RDF/OWL representation of the <strong>EBUCore</strong> schema is given in Annex B. The definitions in <strong>EBUCore</strong> 1.5 
 *  have been refined. The schema structure has been reinforced for registration in EBU's Class 13 in SMPTE. 
 *  The EBU ontology (<strong>EBUCore</strong> RDF implementation) has been updated to complement EBU's CCDM (EBU Tech 3351) 
 *  and improve mapping with other ontologies of the audiovisual sector such as Mediamap.</p>
 *  <p><strong>EBUCore</strong> 1.5 also introduces the schema of a new advanced data model for audio defined in EBU Tech 3364.</p>
 *  <p>More information on EBU metadata activities is provided on the <a href="http://tech.ebu.ch/metadata" targer="_blank">EBU TECHNICAL website</a> 
 *  ({@link "http://tech.ebu.ch/metadat"}).</p>
 * 
 * 
 */

@javax.xml.bind.annotation.XmlSchema(
		namespace = "urn:ebu:metadata-schema:ebuCore_2014", 
		elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
		xmlns = {
				@XmlNs(namespaceURI = "urn:ebu:metadata-schema:ebuCore_2014", prefix = "ebucore")
		})
package ebu.metadata_schema.ebucore_2014;
import javax.xml.bind.annotation.XmlNs;

